server:
  port: 8180

spring:
  profiles:
    active: local
  application:
    name: end2end-testing-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-durations-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC

logging:
  level:
    com.testplatform: INFO
    org.springframework.boot: INFO
    org.springframework.boot.autoconfigure: WARN
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
