server:
  port: 8180

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/testplatform
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/testplatform
  
  security:
    jwt:
      secret: mySecretKey
      expiration: 86400000 # 24 hours

logging:
  level:
    com.testplatform: DEBUG