server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testplatform
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/testplatform
  
  security:
    jwt:
      secret: mySecretKey
      expiration: 86400000 # 24 hours

logging:
  level:
    com.testplatform: DEBUG